sudo: required

services:
  - docker

stages:
  - s1
  - s2

jobs:
  include:
    - stage: s1
      script: ./ci debian-buster.base debian-buster.base.nim
    - script: ./ci debian-stretch.base debian-stretch.base.nim debian-stretch.base.nim.ui
    - script: ./ci debian-stretch.base.wasm.nim
    - stage: s2
      script: ./ci-tag debian-buster-pre-nim debian-buster.base
    - script: ./ci-tag debian-buster-nim-base debian-buster.base.nim
    - script: ./ci-tag debian-pre-nim debian-buster.base
    - script: ./ci-tag nim-base debian-buster.base.nim
    - script: ./ci-tag nim-ui-base debian-buster.base.nim.ui
