FROM yglukhov/nim-ui-base
MAINTAINER Yuriy Glukhov <yuriy.glukhov@gmail.com>
RUN apt-get install -y libsdl2-dev libopenal-dev libvorbis0a libogg0 libgtk-3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
