name: CI

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Build:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    strategy:
      fail-fast: false
      matrix:
        builds:
          - debian-buster.base debian-buster.base.nim debian-buster.base.nim.ui
          # - debian-stretch.base debian-stretch.base.nim debian-stretch.base.nim.ui
          - ubuntu-2204.base ubuntu-2204.base.nim

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    name: ${{matrix.builds}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: |
        ./ci ${{matrix.builds}}

    # - name: Tags
    #   shell: bash
    #   run: |
    #     ./ci-tag debian-buster-pre-nim debian-buster.base
    #     ./ci-tag debian-buster-nim-base debian-buster.base.nim
    #     ./ci-tag debian-pre-nim debian-buster.base
    #     ./ci-tag nim-base debian-buster.base.nim
    #     ./ci-tag nim-ui-base debian-buster.base.nim.ui
